# CONSTRAINTS
# A) DOMAIN CONSTRAINTS-
#1) NOT NULL
#2) DEFAULT
#3) CHECK
#4) ENUM

#A) DOMAIN CONSTRAINTS-
CREATE DATABASE practice2;
CREATE TABLE person(
PERSON_ID INT NOT NULL,
PERSON_F_NAME VARCHAR(50) NOT NULL,
PERSON_L_NAME VARCHAR(50) NOT NULL,
CITY_NAME VARCHAR(50) DEFAULT"-",
PERSON_AGE INT CHECK(PERSON_AGE<60),
PERSON_GENDER ENUM("M","F"));

DESC Person;

INSERT INTO Person VALUES(101,"Ramesh","Jain","Bangalore",55,"M");
INSERT INTO Person VALUES(102,"Suresh","kumar","Mumbai",58,"M");
INSERT INTO Person VALUES(103,"Anisha","Jain","Bangalore",50,"F");
INSERT INTO Person VALUES(104,"Ram","Gupta","pune",40,"M");
INSERT INTO Person VALUES(105,"Jon","Arkin","pune",57,"M");
INSERT INTO Person VALUES(106,"Apeksha","Ekhande","mumbai",21,"F");

SELECT *FROM Person;

# B) KEY CONSTRAINTS-
#1)UNIQUE KEY
#2)PRIMARY KEY
#3)FOREIGN KEY

#1)UNIQUE KEY-

CREATE TABLE Employee(
EMPID INT,
FIRSTNAME VARCHAR(100),
LASTNAME VARCHAR(100),
DEP_ID INT,
UNIQUE(EMPID,DEP_ID)
);

DESC Employee;

INSERT INTO Employee VALUES (1,"A","B",null);
INSERT INTO Employee VALUES (2,"AA","BB",102);
INSERT INTO Employee VALUES (null,"AAA","BBB",103);

SELECT * FROM Employee;

#2)PRIMARY KEY- 

CREATE TABLE Dept(                           #PARENT TABLE
EMPID INT,
FIRSTNAME VARCHAR(100),
LASTNAME VARCHAR(100),
PRIMARY KEY(EMPID)
);

DESC Dept;

INSERT INTO Dept VALUES (1,"X","Y");
INSERT INTO Dept VALUES (2,"XX","YY");
INSERT INTO Dept VALUES (3,"XXX","YYY");

SELECT *FROM Dept;

#3)FOREIGN KEY 

CREATE TABLE Customer(                       #CHILD TABLE
CUST_ID int PRIMARY KEY,
CITY VARCHAR(100),
ID INT,
FOREIGN KEY (ID) REFERENCES DEPT(EMPID)
);
DESC Customer;

INSERT INTO customer VALUES (101,"Pune",1);
INSERT INTO customer VALUES (102,"mumbai",3);
INSERT INTO customer VALUES (103,"Nashik",2);

select *from customer;







